### ISSUE TITLE
Star should only show up if featured result is bookmarked

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search-content#110]
I don't have Facebook bookmarked. There shouldn't be a star next too it.
<img width="951" alt="screen shot 2015-12-04 at 9 31 26 pm" src="https://cloud.githubusercontent.com/assets/3323249/11600679/9fca99ec-9ace-11e5-95ee-9f636396454d.png">

**Comment by chuckharmston** [comment]
The outlined star indicates "recommended", and the solid-filled one is "bookmarked". It's a little confusing, I agree. Thoughts, @bryanbell?

**Comment by johngruen** [comment]
@chuckharmston @bryanbell hmm, yeah, that start is a pretty well mapped icon in FF-land, seems like hte size hierarchy might be enough

**Comment by nchapman** [comment]
I was suggesting to @bryanbell that we should use a lightbulb for these recommendations (at least for now). I think it would be worth trying to get this changed before we show it off too much next week.

**Comment by chuckharmston** [comment]
<img width="283" alt="screen shot 2015-12-06 at 4 47 30 am" src="https://cloud.githubusercontent.com/assets/23885/11613168/957c0208-9bd4-11e5-9d3f-497a0bb99017.png">

Really quick light bulb. Good enough?
