### ISSUE TITLE
Slow response when deleting characters

### ISSUE THREAD

**Issue by nchapman** [mozilla/universal-search-content#111]
It takes a while for the iframe to catch up with the input box when deleting characters:

![screen recording 2015-12-04 at 02 11 pm](https://cloud.githubusercontent.com/assets/3095/11602707/3515665a-9a91-11e5-95a4-9c438ee9f1a5.gif)

**Comment by chuckharmston** [comment]
It looks a bit like a manifestation of https://github.com/mozilla/universal-search-addon/issues/153

**Comment by jaredhirsch** [comment]
The default Firefox popup closes while the user holds down the Backspace key.

Let's do that, too.

Closing in favor of https://github.com/mozilla/universal-search-addon/issues/163
