### ISSUE TITLE
I count six discrete states rendered after one char is typed in URL bar

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search-content#114]
The first screen shot shows how the search box looks after one char is entered, 2-7 show all the states that occur after a second key is pressed. 

![1](https://cloud.githubusercontent.com/assets/3323249/11603241/b9da9744-9ae0-11e5-81a2-572aabd64806.png)
![2](https://cloud.githubusercontent.com/assets/3323249/11603242/b9dab1f2-9ae0-11e5-8dc9-9054165b35d1.png)
![3](https://cloud.githubusercontent.com/assets/3323249/11603243/b9db26aa-9ae0-11e5-830e-7d8454dac950.png)
![4](https://cloud.githubusercontent.com/assets/3323249/11603245/b9dc0610-9ae0-11e5-99fb-dd7331223401.png)
![5](https://cloud.githubusercontent.com/assets/3323249/11603244/b9db6386-9ae0-11e5-9b33-4aa260f2585f.png)
![6](https://cloud.githubusercontent.com/assets/3323249/11603246/b9ed04d8-9ae0-11e5-8090-b78945fda73d.png)
![7](https://cloud.githubusercontent.com/assets/3323249/11603240/b9d68e9c-9ae0-11e5-8545-5e1866dc1004.png)

All of this happens so fast it seems like we could just throttle rendering a bit or something. Here's a gif. @meandavejustice makes a cameo.

![extra-results](https://cloud.githubusercontent.com/assets/3323249/11603402/d7068e76-9ae1-11e5-9f68-77864c317940.gif)

FWIW i did not wind up getting a haircut at Beardy Boys.

**Comment by chuckharmston** [comment]
I think this is a manifestation of https://github.com/mozilla/universal-search-addon/issues/153. @6a68, does that sound right to you?

**Comment by jaredhirsch** [comment]
@johngruen Try grabbing the latest version of the addon; #106 clears out old data when the popup closes, and I've made some addon changes that make it much snappier

**Comment by johngruen** [comment]
@6a68 reopening for the moment until nick pushes the fix and i can confirm...just to be safe

**Comment by jaredhirsch** [comment]
@nchapman time for a release!

**Comment by jaredhirsch** [comment]
I'm pretty sure we did a release at Mozlando. Closing, please reopen if you can still reproduce :-)
