### ISSUE TITLE
A historical search result keeps popping up randomly well after new key presses

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search-content#117]
Very often after a key press, my top search item is replaced with a search for 'sass-lint' which is a search term that i've previously used in this profile. Here's me typing g over and over again, you can clearly see the issue each time:
![sass-lint](https://cloud.githubusercontent.com/assets/3323249/11603567/f3289f30-9ae2-11e5-9381-d5824781e468.gif)

**Comment by chuckharmston** [comment]
Any chance it was https://github.com/mozilla/universal-search-content/issues/105, and has since been addressed?

**Comment by johngruen** [comment]
Hey Chuck, it might be, but the video you linked to in that bug is 404-ing. can you re-upload it?

**Comment by jaredhirsch** [comment]
This looks like #114 to me again. @johngruen can you repro this problem if you use a locally-hosted iframe?

**Comment by jaredhirsch** [comment]
As mentioned in #114, we did a release at Mozlando, so this should definitely be fixed by now. Let's reopen if not.
