### ISSUE TITLE
Replace lodash dependency with more specific modules

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#129]
I noticed that we're including all of [lodash](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/package.json#L23), as well as dependencies for [`lodash.debounce` and `lodash.throttle`](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/package.json#L24-L25).

``` sh
$ grep -irnl "from 'lodash" . --exclude-dir=node_modules
```

| WHERE | WHAT |
| --- | --- |
| [./src/adapters/recommended_adapter.js:2](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/src/adapters/recommended_adapter.js#L2) | `import debounce from 'lodash.debounce';` |
| [./src/adapters/search_suggestions_adapter.js:2](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/src/adapters/search_suggestions_adapter.js#L2) | `import _c from 'lodash/collection'; ... _c.collect(...)` |
| [./src/views/base_view.js:3](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/src/views/base_view.js#L3) | `import flatten from 'lodash/array/flatten';` |
| [./src/views/base_view.js:4](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/src/views/base_view.js#L4) | `import invoke from 'lodash/collection/invoke';` |
| [./src/views/index_view.js:13](https://github.com/mozilla/universal-search-content/blob/95c1e5d69ec044612c79b88fe706d80d8a5af3db/src/views/index_view.js#L13) | `import throttle from 'lodash.throttle';` |

I think we can probably remove the `lodash` dependency switch to the following smaller modules:
- `lodash/collection/collect` to [`lodash.map`](https://www.npmjs.com/package/lodash.map)
- `lodash/array/flatten` to [`lodash.flatten`](https://www.npmjs.com/package/lodash.flatten)
- `lodash/collection/invoke` to [`lodash.invoke`](https://www.npmjs.com/package/lodash.invoke)

**Comment by jaredhirsch** [comment]
PRs welcome. I'd _much_ rather just include all of lodash, because nobody cares about 10 extra KB.
