### ISSUE TITLE
Down arrow opens an empty popup

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#130]
### Steps to reproduce:
1. Type in "cilan" into the address bar.
2. Mine auto completes to "cilantro" as the first search result.
3. Press the down arrow to select the "cilantro" result.
4. Press the right arrow to close the search iframe.
5. Press the down arrow again.
### Actual results:

Pop up re-opens, but is blank:

<img width="1283" alt="window" src="https://cloud.githubusercontent.com/assets/557895/11700058/9545597e-9e95-11e5-89fb-cc2593744190.png">

**Comment by jaredhirsch** [comment]
This is an addon bug. Closing in favor of https://github.com/mozilla/universal-search-addon/issues/161
