### ISSUE TITLE
Long typed URLs are incorrectly treated as searches

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#131]
If a really long string is typed into the urlbar, we show the option to search for the string:

<img width="488" alt="screenshot 2015-12-09 22 55 16" src="https://cloud.githubusercontent.com/assets/96396/11706595/fad49ee4-9ec7-11e5-85ef-c0ac2f28a87c.png">

However, if that really long string happens to look URL-ish, we should (but don't) detect that the string is navigable:

<img width="885" alt="screenshot 2015-12-09 22 53 12" src="https://cloud.githubusercontent.com/assets/96396/11706568/c949f89c-9ec7-11e5-8823-379aa1649fc1.png">

When the user hits Enter, if the search term is probably a URL, we should try to navigate to it. I'm not sure why this is no longer working; in the past, we just shoved a string into the urlbar, and let Firefox figure out, via its [remarkably complex "uri fixup" service](https://dxr.mozilla.org/mozilla-central/source/docshell/base/nsDefaultURIFixup.cpp), whether a given thing looks url-ly or searchy. Seems like probably an addon bug, but I'll leave this here for the moment.

Severity is really low, in the sense that users can still complete their tasks:
- if a user hits Enter, they will successfully be taken to the URLish page.
- if a user searches for some super long URL, they'll probably see _something_ relevant in the search results page
### Steps to reproduce:
1. Search for a delicious sandwich by typing "banh mi" in the address bar.
2. Your browser should redirect to https://search.yahoo.com/yhs/search?p=banh+mi&ei=UTF-8&hspart=mozilla&hsimp=yhs-002 (See **Figure 1**)
3. Focus the address bar and press the down arrow twice. You should see the previous URL in the iframe results. (See **Figure 2**)
4. Select the search result and your browser should redirect to https://us.search.yahoo.com/search?fr=yhs-invalid&p=https%3A%2F%2Fsearch.yahoo.com%2Fyhs%2Fsearch%3Fp%3Dbanh%2Bmi%26ei%3DUTF-8%26hspart%3Dmozilla%26hsimp%3Dyhs-002 (which is now ironically search results for Yahoo! search, and NOT delicious sandwiches -- See **Figure 3**).
### Expected results:

If the search result looks like a URL, we should go directly to that URL instead of passing a URL-esque search term to Yahoo!
### Screenshots:

<img width="1179" alt="banh_mi_-_-_yahoo_search_results" src="https://cloud.githubusercontent.com/assets/557895/11700331/384dff6c-9e97-11e5-8fe4-5b502622cd23.png">
**Figure 1:**

---

<img width="1179" alt="banh_mi_-_yahoo_search_results" src="https://cloud.githubusercontent.com/assets/557895/11700426/c1fcd09e-9e97-11e5-87b4-664669838f1b.png">
**Figure 2:**

---

<img width="1179" alt="https___search_yahoo_com_yhs_search_p_banh_mi_ei_utf-8_hspart_mozilla_hsimp_yhs-002_-_yahoo_search_results" src="https://cloud.githubusercontent.com/assets/557895/11700306/17d2b8fe-9e97-11e5-8690-f57938b464b3.png">
**Figure 3:**

**Comment by jaredhirsch** [comment]
Here's some addon code that takes a swing at deciding if a string is probably a URL or not:

https://github.com/Mardak/enterSelects/blob/master/lib/main.js#L39

**Comment by jaredhirsch** [comment]
Closing in favor of https://github.com/mozilla/universal-search-addon/issues/190
