### ISSUE TITLE
Inconsistent search results when searching via address bar or iframe dropdown

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#132]
### Steps to reproduce:
1. Type the word "maize" in the address bar and press Enter.
2. You're redirected to https://search.yahoo.com/yhs/search?p=maize&ei=UTF-8&hspart=mozilla&hsimp=yhs-002 (See **Figure 1**)
3. Type the word "maize" in the address bar, and select one of the search results in the iframe content.
4. You're redirected to https://us.search.yahoo.com/search?fr=yhs-invalid&p=maize (See **Figure 2**)
### Actual results:

Depending on whether I search via the address bar or using the dropdown, I'm directed to either _search.yahoo.com_ or _**us.**search.yahoo.com_ (which have subtly different UIs and results).

As a user, I'd expect both methods to return similar results and take me to the same page. Oddly, both search interfaces return slightly different results in different orders, which is mildly frustrating.
### Screenshots:

<img width="1440" alt="maize_-_-_yahoo_search_results" src="https://cloud.githubusercontent.com/assets/557895/11701003/10f6e72c-9e9b-11e5-82b7-ac1e1a3e6984.png">
**Figure 1:**

---

<img width="1440" alt="maize_-_yahoo_search_results" src="https://cloud.githubusercontent.com/assets/557895/11701018/24c7e6d4-9e9b-11e5-8420-50b2c12b78f5.png">
**Figure 2:**

**Comment by jaredhirsch** [comment]
@pdehaan Not sure I see any actual end user value in worrying about this one. Closing, sorry!
