### ISSUE TITLE
Only render the popup once per search

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-content#135]
Currently, we render the tiny machine results whenever they arrive; this tends to be just late enough that it makes the popup seem like it's sloppily cascading open, and not popping cleanly open.

Let's set a very short timeout, and if tiny machine hasn't arrived in time, don't render it.

**Comment by johngruen** [comment]
this seems like a good idea.

**Comment by jaredhirsch** [comment]
I'm going to close this in favor of first measuring the render performance of the iframe, and looking for sources of jank (rendering dropping below about 30 frames/second). Once we have data, I'll open some bugs to optimize leading sources of lag.
