### ISSUE TITLE
Don't assume a . in a query string means i'm looking for a URL

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search-content#142]
This is a major annoyance in the current awesome bar. Here's what happens: 

![screen shot 2015-12-14 at 1 36 58 pm](https://cloud.githubusercontent.com/assets/3323249/11790058/ce05f6ee-a267-11e5-8a94-cbbe34cb036a.png)

In this case, i'd be much better served if the first was a result since visiting http://immutable.js will obviously lead nowhere.

Maybe certain filetype suffixes should trigger a search as the primary result to avoid this case.

**Comment by jaredhirsch** [comment]
Reopening on the addon side.
