### ISSUE TITLE
ensure only one row is highlighted in popup

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-content#32]
Rows in the popup can be highlighted by either mouse hovering, or keying up/down. Currently, if you switch between key navigation and mouse navigation while the popup is open, you'll see two highlighted rows in the popup.

Simplest fix is probably to stop applying the mouse hover class via CSS, and apply it via JS instead. Then, the click and key handlers could both just remove `.selected` from all rows, and apply it to the one most recently selected row. Getting fancier, we could instead reify the selected state as a Selection object on the JS side, so that, on click or on navigational-key, we wouldn't have to touch the DOM to grab the selected item; instead, we'd ask the Selection which item it's attached to. @nchapman might have more specific ideas about the best approach for the current codebase.

This could be a fun, not too demanding front-end bug, in case anybody is feeling frisky (@pdehaan? @johngruen? @kitcambridge? @edmoz?).

**Comment by nchapman** [comment]
Yeah the current solution surrounding this is a hack in almost every way. We should do something better. My preference is actually to have a separate highlight for the keyboard vs the mouse, but this has so far been controversial.

**Comment by jaredhirsch** [comment]
> My preference is actually to have a separate highlight for the keyboard vs the mouse

I'm open to this, curious why you're a fan of this approach?

What about setting some state on a singleton Selection or Highlight object that indicates whether it's a mouse or keyboard source?

**Comment by jaredhirsch** [comment]
Per convo in engineering meeting: updating the urlbar on mousemove makes Safari kinda flickery / janky. If we just have a separate hover style and make the keyboard dominant, i.e. moving keys but not the mouse updates the urlbar, it'll be easier to fix and also lead to better performance.

This is something we'll probably revisit, so this can just be a provisional solution.

**Comment by jaredhirsch** [comment]
This seems fixed to me?

**Comment by jaredhirsch** [comment]
Yeah, definitely fixed by #43. Closing.
