### ISSUE TITLE
Add Gulp

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#36]
Not sure if we want to add Grunt to this repo to run ESLint, Webpack, generate CHANGELOG files, and manage npm versioning (via **grunt-bump** or whatever).

**Comment by pdehaan** [comment]
FWIW, I was trying to casually sneak Grunt into https://github.com/mozilla/universal-search-addon/pull/50.

**Comment by lmorchard** [comment]
FWIW, I'm a way bigger fan of [Gulp](http://gulpjs.com/) than Grunt. I just kind of got lost in Grunt config files where Gulp pipelines just clicked for me very quickly. But, your mileage may vary. 

Not sure if this helps the case, but [I'd submitted a PR](https://github.com/mozilla/universal-search-content/pull/15) with [a gulp build chain](https://github.com/lmorchard/universal-search-content/blob/big-gulp/gulpfile.js) that could produce multiple versions of the iframe content. I think that got sidelined with the switch to the addon (vs gecko patch) and a rebuild of the iframe

**Comment by nchapman** [comment]
> Not sure if this helps the case, but I'd submitted a PR with a gulp build chain that could produce multiple versions of the iframe content. I think that got sidelined with the switch to the addon (vs gecko patch) and a rebuild of the iframe

Yes this was great. I was planning on bringing it back... just haven't had a chance to sort that out. I agree with choosing Gulp over Grunt as well.

**Comment by pdehaan** [comment]
Ah cool, I was just playing w/ Gulp.

This was my rough _gulpfile.babel.js_ file (see github.com/gulpjs/gulp/issues/830 - requires **gulp@3.9** or later):

``` js
const del = require('del');
const eslint = require('gulp-eslint');
const gulp = require('gulp');
const webpack = require('webpack');

const webpackConfig = require('./webpack.config.js');

gulp.task('eslint', function () {
  return gulp.src(['*.js', 'src/**/*.js'])
    .pipe(eslint())
    .pipe(eslint.failOnError());
});

gulp.task('clean:dist', function (callback) {
  del(['dist'], callback);
});

gulp.task('webpack', ['clean:dist'], function (callback) {
  webpack(webpackConfig).run(function (err, stats) {
    callback(err);
  });
});

gulp.task('default', ['lint']);
gulp.task('lint', ['eslint']);
gulp.task('build', ['lint', 'webpack']);
```

**Comment by pdehaan** [comment]
Grunt is out. Gulp is in. Updated bug title.

**Comment by jaredhirsch** [comment]
@pdehaan Let's just reuse the build chain from Idea Town!
