### ISSUE TITLE
Substitute history icon for search suggestions if they've been used before 

### ISSUE THREAD

**Issue by johngruen** [mozilla/universal-search-content#4]
Per @bryanbell's mockup:

![image 2015-04-07 at 12 46 33 pm](https://cloud.githubusercontent.com/assets/3323249/7031953/59b60c06-dd3d-11e4-9bb9-5608a63cbad7.png)

**Comment by jaredhirsch** [comment]
hmm, this is actually something the browser should take care of, and might or might not be easy to send down, I honestly am not sure

**Comment by nchapman** [comment]
Fixed in #21.
