### ISSUE TITLE
Tab results should be styled differently

### ISSUE THREAD

**Issue by nchapman** [mozilla/universal-search-content#40]
![screen shot 2015-07-22 at 12 58 14 pm](https://cloud.githubusercontent.com/assets/3095/8835768/5a71971e-3071-11e5-9bd9-dc755481ff17.png)

This should look like a tab and not show the `mozaction:` url.

**Comment by chuckharmston** [comment]
This got fixed in 6fcfb8cc5e068e75edb093e0a2d5ff32f57db1c0
