### ISSUE TITLE
Add CHANGELOG?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#41]
It may be nice to have a handy CHANGELOG to this repo so we can see what changes betweenst releases, etc.

Possibly use something like:
- https://www.npmjs.com/package/gulp-changelog-release
- https://www.npmjs.com/package/gulp-conventional-changelog

(ref: https://github.com/mozilla/universal-search-addon/issues/65)

**Comment by pdehaan** [comment]
**Disclaimer:** This also means we'd need to have commit guidelines (similar to **fxa-content-server**'s [Git Commit Guidelines](https://github.com/mozilla/fxa-content-server/blob/master/CONTRIBUTING.md#git-commit-guidelines)).

**Comment by jaredhirsch** [comment]
We seem to be doing fine without this, closing.
