### ISSUE TITLE
Lint code on Git prepush hook

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#49]
Ref: https://github.com/mozilla/universal-search-addon/pull/69

Probably just use [**husky**](https://www.npmjs.com/package/husky) like we did for Chronicle and keeps it consistent w **mozilla/universal-search-addon**. Just a wrapper for `gulp lint` so code is linted before we check in and have Travis re-lint it.

**Comment by pdehaan** [comment]
I'll do this after we merge the #44 PR (which adds Gulp+ESLint)

**Comment by jaredhirsch** [comment]
No thanks. I often want to push an incomplete branch, and the linter integration is a frequent annoyance.

TravisCI lints PRs for us, so we can rely on that instead.
