### ISSUE TITLE
Favicons: render favicon data-uri

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-content#64]
We currently use a prototype favicon proxy service[1] to grab favicons. We don't want to keep using it.

Once https://github.com/mozilla/universal-search-addon/issues/139 lands, the addon will be sending over a usable, serialized favicon image with each local history result.

This bug collects work to render the serialized image (just set the data-uri as the favicon img src?).

[1] https://github.com/nchapman/summarizer-server

**Comment by chuckharmston** [comment]
This was addressed in 27c38bb.
