### ISSUE TITLE
Favicons: remove summarizer

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-content#65]
We currently use a prototype favicon proxy service[1] to grab favicons. We don't want to keep using it.

Once https://github.com/mozilla/universal-search-addon/issues/139 lands, the addon will be sending over a usable, serialized favicon image with each local history result.

Task here: once #64 lands, remove all references to the summarizer server from the front-end.

[1] https://github.com/nchapman/summarizer-server

**Comment by chuckharmston** [comment]
This was addressed in 27c38bb.
