### ISSUE TITLE
Search dropdown leaks outside of Firefox when browser is partially offscreen

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#69]
I noticed that if my browser is partially offscreen, then the dropdown button gets pushed outside of the browser window, which was a bit unexpected.

![add-ons_manager_and_favicons_not_rendering_for_certain_sites_ _issue__68_ _mozilla_universal-search-content_and_auto-tools_projects_mozbase_-_mozillawiki_and_privacy_error](https://cloud.githubusercontent.com/assets/557895/11221342/7e14f454-8d19-11e5-9b18-934e04ae7516.png)

**Comment by jaredhirsch** [comment]
This is not a bug, it's a feature: Firefox does the same thing.

Surprised me too when I first started working on this stuff.
