### ISSUE TITLE
Consider excluding search engine results from history items

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-content#72]
<img width="1179" alt="screen shot 2015-11-18 at 9 13 50 am" src="https://cloud.githubusercontent.com/assets/23885/11246392/b687c8be-8dd4-11e5-8ed0-13577f11b9a1.png">

Those two Google items are a bit awkward, and are getting in the way of mo' real-er content. Perhaps we should exclude results from known search engine domains?

**Comment by jaredhirsch** [comment]
This is now done! Hooray! Closing.
