### ISSUE TITLE
Little Machine preview images with white backgrounds look strange

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-content#79]
Example:

<img width="917" alt="screen shot 2015-11-23 at 12 35 43 pm" src="https://cloud.githubusercontent.com/assets/23885/11347690/ebef98d8-91df-11e5-9f7a-dff98da15da0.png">

**Comment by chuckharmston** [comment]
One option: we could add an inset shadow over the image. That might look like this:

<img width="187" alt="screen shot 2015-11-23 at 12 42 52 pm" src="https://cloud.githubusercontent.com/assets/23885/11347734/10d34852-91e0-11e5-8ae9-45e8251952d4.png">
<img width="185" alt="screen shot 2015-11-23 at 12 42 05 pm" src="https://cloud.githubusercontent.com/assets/23885/11347735/10e50fba-91e0-11e5-8aba-f3b50788be38.png">

It doesn't look amazing, but it helps define the bounds of the logo for GitHub without messing up logos with colored backgrounds.

Thoughts @bryanbell?

**Comment by bryanbell** [comment]
yes, borders (inset shadows) are good and right.  Engage!
