### ISSUE TITLE
Use includePaths for normalize dependency?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/universal-search-content#85]
I randomly noticed in [src/styles/main.scss](https://github.com/mozilla/universal-search-content/blob/95ccf8ea31f8514aea2e597ba31fed5cd86f653e/src/styles/main.scss#L1) that we're doing a not-so-fancy `@import '../../node_modules/...` to bring in the **normalize** dependency.

I'm not a webpack or Sass expert, but I think we may be able to simplify that slightly using the **node-normalize-scss** dependency's `includePaths` var.

Maybe something like this...
1. Change [/src/styles/main.scss:1](https://github.com/mozilla/universal-search-content/blob/95ccf8ea31f8514aea2e597ba31fed5cd86f653e/src/styles/main.scss#L1) to:
   
   ``` scss
   @import 'normalize';
   ```
2. Add this line to [webpack.config.js:2](https://github.com/mozilla/universal-search-content/blob/95ccf8ea31f8514aea2e597ba31fed5cd86f653e/webpack.config.js#L2):
   
   ``` js
   const normalize = require('node-normalize-scss');
   ```
3. Finally add the **normalize** `includePaths[]` to the sass-loader in [webpack.config.js:23](https://github.com/mozilla/universal-search-content/blob/95ccf8ea31f8514aea2e597ba31fed5cd86f653e/webpack.config.js#L23):
   
   ``` js
   { test: /\.scss$/, loader: 'style!css!sass?sourceMap&includePaths[]=' + normalize.includePaths },
   ```

**Comment by jaredhirsch** [comment]
@pdehaan PRs welcome :-)

**Comment by pdehaan** [comment]
@6a68 As you wish, #138.
