### ISSUE TITLE
Calculate dominant color of favicon on the fly

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search-content#91]
For the purposes of doing something like this:

![image 2015-11-25 at 12 36 59 pm](https://cloud.githubusercontent.com/assets/23885/11433409/d4e15fc2-9479-11e5-9ef1-5de1408d3bfb.png)

Dependencies:
- #90 
- #64
- #65 (sort of)
- mozilla/universal-search-addon/#139

**Comment by chuckharmston** [comment]
We might be able to use this library: https://www.npmjs.com/package/color-thief

**Comment by chuckharmston** [comment]
So, doing this "correctly" is slow. Some of the algorithms I played with were 100-200ms a shot, and that's not even close to good enough. So I tried something [cheap and dirty](http://codepen.io/anon/pen/BoXorj):

<img width="812" alt="screen shot 2015-11-28 at 2 31 38 pm" src="https://cloud.githubusercontent.com/assets/23885/11454006/d587e4fa-95dc-11e5-86ea-2aed895ad4e6.png">

(Netflix, Facebook, Yahoo, The Guardian, TechCrunch, Google, Amazon, Apple, Firefox, Mozilla, Chrome, OkCupid, respectively).

This returns the mode color after iterating over each nonwhite pixel in the image with alpha > 0.8.
It's consistently less than 5 milliseconds per 16x16 and 32x32 image. It's not perfect, as the Netflix example shows, but it's a good start.

@bryanbell thoughts?

**Comment by chuckharmston** [comment]
Thinking more...this all sucks. What we really want here is an Apple Touch Icon, if one is available. Maybe we use the favicon as a fallback?

I wrote [some code](https://github.com/mozilla/zamboni/blob/master/mkt/websites/helpers.py) for Marketplace to find an icon for a site, using a number of different sources from the site itself. Try it out:

https://marketplace.firefox.com/api/v2/websites/scrape/?url=http://nickchapman.me

The images returned for the sites I used in the demo above:
- Netflix: none
- [Facebook](https://cloud.githubusercontent.com/assets/23885/11453884/9ac3418c-95d9-11e5-9f83-2b9814d27137.png)
- [Yahoo](https://cloud.githubusercontent.com/assets/23885/11453886/b4076d4e-95d9-11e5-8a88-2492db156147.png)
- [The Guardian](https://cloud.githubusercontent.com/assets/23885/11453889/ccfb6d82-95d9-11e5-847d-256b68f5ad15.png)

Not amazing, but it's better than what we have available to us with the favicon color guessing, right? And it's certainly dumb logic that can be improved/augmented with other services.

The problem: it requires a second request to a second service. Perhaps the right approach is to get an icon in this way, if possible to do so in a reasonable time, otherwise we show the favicon as in the Codepen above. Or we can get the image and store as an annotation on the addon side.

**Comment by nchapman** [comment]
Yeah we'd definitely rather have the apple touch icon, but we can work up to that. I love what you got working for the dominant color! Maybe we could choose to use a white background on the favicon if a certain percentage of the image is transparent?

**Comment by nchapman** [comment]
We should be able to cache the calculated color in `localStorage` right?

**Comment by chuckharmston** [comment]
> We should be able to cache these in localStorage right?

Yeah, although if we're talking about 1-2ms to determine the color, it might actually be faster to just calculate it on the fly.

**Comment by chuckharmston** [comment]
With [some updates](http://codepen.io/anon/pen/BoXorj) I have it to this:

<img width="813" alt="screen shot 2015-11-30 at 12 53 25 pm" src="https://cloud.githubusercontent.com/assets/23885/11482671/626764a6-9761-11e5-99dd-f6c674cbfe53.png">

**Comment by chuckharmston** [comment]
On average, this takes about 2⅙ms per icon. Totally passable, I think, if the results are good enough.

**Comment by bryanbell** [comment]
looks great to me man.

**Comment by chuckharmston** [comment]
Worth noting: this will not work unless used with the version of the addon that includes https://github.com/mozilla/universal-search-addon/pull/147, as `<canvas>` is subject to the same-origin policy, and before that commit the addon reported favicon URLs, rather than data URIs.
