### ISSUE TITLE
Machine image sometimes collapses when popup is narrow

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-content#94]
This only seems to affect certain sites, and I'm not sure why. The zillow little machine response seems to consistently have this problem, though:

![](https://www.dropbox.com/s/dq1loew1rqp2adl/Screenshot%202015-11-30%2015.46.51.png?dl=0&raw=true)

![](https://www.dropbox.com/s/6iah3ilcelciuo7/Screenshot%202015-11-30%2015.48.46.png?dl=0&raw=true)

**Comment by chuckharmston** [comment]
What's the smallest width we should be concerned with supporting? Should we have a larger "how do we make this responsive?" brainstorm session in Orlando?

**Comment by chuckharmston** [comment]
This will be addressed by #92.
